global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-mikhail.2sem.students-projects.ru
    tlsSecretName: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 80
  image: mishamancik/sausage-frontend:latest
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "300m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  image: mishamancik/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 5
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: backend
          controlledResources:
            - cpu
            - memory

backend-report:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  image: mishamancik/sausage-backend-report:latest
  containerPort: 8080
  env:
    port: "8080"
    mongoUri: mongodb://report:reportpassword@mongodb:27017/reports?authSource=reports
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 75

infra:
  postgresql:
    image: postgres:16
    containerPort: 5432
    storage: 1Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "300m"
    env:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
      POSTGRES_DB: sausage-store
      PGDATA: /var/lib/postgresql/data/pgdata
  mongodb:
    image: mongo:7.0
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "300m"
    init:
      enabled: true
      reportService:
        database: reports
        username: report
        password: reportpassword
      backendService:
        database: sausage-store
        username: reports
        password: reportspassword
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"
