{{- if and .Values.global.vault.enabled .Values.global.vault.vaultToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-vault
type: Opaque
stringData:
  token: {{ .Values.global.vault.vaultToken | quote }}
{{- end }}
